//
// Created by Paul Ross on 21/05/2021.
//

#ifndef PYTHONCPPHOMOGENEOUSCONTAINERS_TEST_FUNCTIONAL_H
#define PYTHONCPPHOMOGENEOUSCONTAINERS_TEST_FUNCTIONAL_H

#include "TestFramework.h"

void test_functional_all(TestResultS &test_results);

#endif //PYTHONCPPHOMOGENEOUSCONTAINERS_TEST_FUNCTIONAL_H
