//
// Created by Paul Ross on 22/05/2021.
//

#ifndef PYTHONCPPHOMOGENEOUSCONTAINERS_TEST_PERFORMANCE_H
#define PYTHONCPPHOMOGENEOUSCONTAINERS_TEST_PERFORMANCE_H

#include "test_common.h"

void test_performance_all(TestResultS &test_results);

#endif //PYTHONCPPHOMOGENEOUSCONTAINERS_TEST_PERFORMANCE_H
